### ISSUE TITLE
Adding the profile alignment capabilities of famsa to pyfamsa

### ISSUE THREAD

**Issue by Thernn88** [althonos/pyfamsa#5]
Hello!

Would you mind adding the profile alignment capabilities to pyfamsa?

Profile-profile alignments (available by specifying two input FASTA files; introduced in revision 2.2.0).

Edit: I also wanted to express my gratitude for making these bindings. The package made it very easy to incorporate FAMSA into my phylogenetic pipeline. Surprisingly, it was also faster than calling the compiled executable.

**Comment by althonos** [comment]
Hi @Thernn88 !

I'll see what I can do, a profile is just a list of `GappedSequence` so it should be quite easy to implement, although I need to improve the interface of `GappedSequence` to allow creation from the Python side. 

> Edit: I also wanted to express my gratitude for making these bindings. The package made it very easy to incorporate FAMSA into my phylogenetic pipeline. Surprisingly, it was also faster than calling the compiled executable.

Really happy to hear that, that's the goal to make it easier and faster when possible! Maybe for SAPPHYRE I can also interest you in [PyHMMER](https://github.com/althonos/pyhmmer) for running `hmmsearch` the same way :wink:

**Comment by Thernn88** [comment]
Thank you!

We've tried using PyHMMER, but it wouldn't jive with our methodology. I wasn't the dev working on incorporation, but IIRC it had something to do with incompatibility with the output results PyHMMER returned.

Currently, the workflow is as follows. We use HMMER to process Diamond hits. HMMER is simply incapable of processing millions of reads against thousands of HMMprofiles in any reasonable timeframe. Additionally, but importantly, using Diamond allows us to identify the set of closest reference taxa from a very broad reference set. This leads to **significantly** improved HMMprofiles. We do this for reasons which I won't go into length here. 

We serially-parallelize HMMER. For example, given 32 processes, we call 32 instances of HMMER (default cpu). To summarize, each process grabs a loci from our list, builds a custom hmm profile (using our identified closest refs), and then HMMsearches queries for which Diamond recorded a hit for the loci against this HMM profile.

We will reach out with some questions soon.

**Comment by althonos** [comment]
Hi @Thernn88,

I implemented the profile-profile alignment in `v0.5.0`. Check the new `Aligner.align_profiles` method, which takes two `Alignment` objects to align together. `Alignment` can now be created programmatically from an iterable of `GappedSequence` objects, and `GappedSequence` can be created from an identifier and a (gappy) sequence similar to `Sequence`.
